-- create schema and set search_path so objects are created inside to_do_list
CREATE SCHEMA IF NOT EXISTS to_do_list;
SET search_path TO to_do_list, public;

-- employee table
CREATE TABLE IF NOT EXISTS employee (
                                        employeeId bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    firstname varchar(50),
    lastname varchar(50),
    email varchar(50),
    department varchar(50)
    );

-- task table
CREATE TABLE IF NOT EXISTS task (
                                    taskId bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    name varchar(50),
    description varchar(250),
    createDate timestamp,
    deadline timestamp,
    status varchar(30),
    statusUpdate timestamp,
    assignee bigint REFERENCES employee(employeeId),
    reporter bigint REFERENCES employee(employeeId)
    );

-- Quartz history table
CREATE TABLE IF NOT EXISTS qrtz_job_history (
                                                id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    jobName varchar(50),
    jobGroup varchar(50),
    jobDescription varchar(200),
    jobRunTime bigint,
    triggerName varchar(50),
    triggerGroup varchar(50),
    triggerDescription varchar(200),
    triggerType varchar(10),
    uuid varchar(50),
    result text,
    fireTime timestamp,
    scheduledFireTime timestamp,
    previousFireTime timestamp,
    nextFireTime timestamp
    );

-- create unique index if missing
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.relname = 'qrts_job_history_idx' AND n.nspname = 'to_do_list'
  ) THEN
CREATE UNIQUE INDEX QrtzHistory ON qrtz_job_history(id, jobName, jobGroup, triggerName, triggerGroup);
END IF;
END$$;