create schema to_do_list;

drop table if exists to_do_list.employee;
create table to_do_list.employee (
     employeeId bigint generated by default as identity (start with 1) NOT NULL PRIMARY KEY,
     firstname varchar(50),
     lastname varchar(50),
     email varchar(50),
     department varchar(50)
);

drop table if exists to_do_list.task;
create table to_do_list.task (
     taskId bigint generated by default as identity (start with 1) NOT NULL PRIMARY KEY,
     name varchar(50),
     description varchar(250),
     createDate timestamp,
     deadline timestamp,
     status varchar (30),
     statusUpdate timestamp,
     assignee bigint references to_do_list.employee,
     reporter bigint references to_do_list.employee
);

--Quartz Schema
drop table if exists to_do_list.qrtz_job_history;
CREATE TABLE to_do_list.qrtz_job_history  (
    id bigint generated by default as identity (start with 1) NOT NULL PRIMARY KEY ,
    jobName varchar(50),
    jobGroup varchar(50),
    jobDescription varchar(200),
    jobRunTime bigint,
    triggerName varchar(50),
    triggerGroup varchar(50),
    triggerDescription varchar(200),
    triggerType varchar(10),
    uuid varchar(50),
    result text,
    fireTime timestamp,
    scheduledFireTime timestamp,
    previousFireTime timestamp,
    nextFireTime timestamp
);

CREATE UNIQUE INDEX QrtzHistory on to_do_list.qrtz_job_history(id, jobName, jobGroup, triggerName, triggerGroup);
