create schema to_do_list;

drop table if exists to_do_list.employee;
create table to_do_list.employee (
     employeeId bigint generated by default as identity (start with 1) NOT NULL PRIMARY KEY,
     firstname varchar(50),
     lastname varchar(50),
     department varchar(50)
);

drop table if exists to_do_list.task;
create table to_do_list.task (
     taskId bigint generated by default as identity (start with 1) NOT NULL PRIMARY KEY,
     name varchar(50),
     description varchar(250),
     createDate timestamp,
     deadline timestamp,
     status varchar (30),
     assignee bigint references to_do_list.employee,
     reporter bigint references to_do_list.employee
);